version: '3.7'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DB_SERVER=tcp:inovabyte2.database.windows.net,1433
      DB_DATABASE=TiendaOnline32
      DB_USERNAME=geovanydominguez
      DB_PASSWORD=Flacodeoro55
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
