version: '3.7'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mssql+pyodbc://geovanydominguez:Flacodeoro55@inovabyte2.database.windows.net:1433/inovabyte?driver=ODBC+Driver+17+for+SQL+Server"
